name: faiss_test
channels:
  - conda-forge
  - defaults
dependencies:
  - jsonschema=4.4.0
  - python=3.12
  - pip=24.1.1
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - anyio=3.7.1
  - attrs=23.1.0
  - beautifulsoup4=4.12.2
  - blinker=1.7.0
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cssselect=1.2.0
  - decorator=5.1.1
  - distro=1.8.0
  - filelock=3.13.1
  - flask=3.0.0
  - frozenlist=1.4.0
  - google-api-core=2.14.0
  - google-auth=2.25.1
  - google-cloud-bigquery=3.13.0
  - google-cloud-core=2.3.3
  - google-crc32c=1.5.0
  - google-resumable-media=2.6.0
  - grpcio=1.59.3
  - grpcio-status=1.59.3
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.25.2
  - idna=3.6
  - ipykernel=6.28.0
  - ipython=8.18.1
  - iso8601=2.1.0
  - itsdangerous=2.1.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jupyter_client=8.6.0
  - jupyter_core=5.6.0
  - lxml=5.1.0
  - markupsafe=2.1.3
  - multidict=6.0.4
  - nest-asyncio=1.5.8
  - nltk=3.8.1
  - numpy=1.26.2
  - openai=1.3.7
  - packaging=23.2
  - pandas=2.1.3
  - parso=0.8.3
  - pillow=10.2.0
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.41
  - proto-plus=1.22.3
  - protobuf=4.25.1
  - psutil=5.9.7
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygame=2.5.2
  - pygments=2.17.2
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - pytz=2023.3.post1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - regex=2023.10.3
  - requests=2.31.0
  - rsa=4.9
  - six=1.16.0
  - sniffio=1.3.0
  - soundfile=0.12.1
  - soupsieve=2.5
  - stack-data=0.6.3
  - tenacity=8.2.3
  - tqdm=4.66.1
  - traitlets=5.14.0
  - twitchio=2.8.2
  - typing_extensions=4.8.0
  - tzdata=2023.3
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - websockets=12.0
  - werkzeug=3.0.1
  - yarl=1.9.4
  - pip:
      - annotated-types==0.6.0
      - asttokens==2.4.1
      - comm==0.2.0
      - debugpy==1.8.0
      - elevenlabs==0.2.26
      - executing==2.0.1
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - newspaper3k==0.2.8
      - pydantic==2.5.2
      - pydantic_core==2.14.5
      - requests-file==2.0.0
      - sgmllib3k==1.0.0
      - sounddevice==0.4.6
      - SpeechRecognition==3.10.1
      - tinysegmenter==0.3
      - tiktoken==0.5.2
      - tldextract==5.1.1
      - tornado==6.4
