######
#USAGE
# - 

#CONFIG
env_filename: 'config-games-in.env'
env_dirname: 'config'

#games_countdown params
#TODO
server_guild_id: '1110236483505377400' #TODO: update to take from environment variable 
server_channel_id: '1145905547946762252' #TODO: update to take from environment variable
discord_games_countdown_username: 'yo daddy'
discord_games_countdown_default_minutes: 8 #not in use, to be implemented
